### ISSUE TITLE
BUFFER_OVERRUN

### ISSUE THREAD

**Issue by James1847** [hroussille/multicall-decode#1]
Does anyone can help me? the transaction is https://etherscan.io/tx/0x14ab6f222c1f474011576607a4f16631a20289f37129f90f8cba054f23e68d07?__cf_chl_tk=rNVRA10jARuKSKN0wFmhAdZ7weFbBlnytuKiJzdlg0M-1649292558-0-gaNycGzNCRE, and when I use the method above, always gives me the error:

reason: 'data out-of-bounds',
code: 'BUFFER_OVERRUN',
length: 0,
offset: 32

**Comment by hroussille** [comment]
You are probably not giving the proper parameters to the `encode` function which expect an abi.encoded `bytes[]`.

I'll update the package today with `decodeRaw` for the basic use case of full abi encoded `bytes[]` input and `decodeCalls` that will receive a decoded `bytes[]` that will be better for your use case given that your tx calldata must be split since it includes a `uint` as first parameter which makes the usage of multicall-decode not practical at all.

**Comment by hroussille** [comment]
The package is updated, an example usage of `decodeCalls` on your specific tx would be : 

```js
const Web3 = require("web3");
const { decodeCalls } = require("multicall-decode");

const ENDPOINT = "https://mainnet.infura.io/v3/API_KEY";

const web3 = new Web3(ENDPOINT);

async function main() {
  const TX_HASH = "0x14ab6f222c1f474011576607a4f16631a20289f37129f90f8cba054f23e68d07";
  const tx = await web3.eth.getTransaction(TX_HASH);
  
  // ABI decode the calldata without the function identifier
  const decoded = await web3.eth.abi.decodeParameters(["uint", "bytes[]"], tx.input.slice(10));

  // Call decodeCalls with the decoded bytes[] : parameter 1 in the function signature
  console.log(await decodeCalls(decoded[1]));
}

main();
```

Which outputs : 

```json
[
  [
    {
      signature: 'swapExactTokensForTokens(uint256,uint256,address[],address)',
      _id: 0,
      parameters: [Array],
      valid: true
    }
  ],
  [
    {
      signature: 'unwrapWETH9(uint256,address)',
      _id: 0,
      parameters: [Array],
      valid: true
    }
  ]
]
```
